version: '3.7'
services:
  backend:
    build: ./backend
    ports:
      - 3001:3001
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.40'
          memory: 300M
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 200M
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 500M
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
